// 건강지도(/health-map) 신체 부위 존의 "구조" 정의.
// - keywords: DB의 health_benefits.category 문자열에 포함되는지(includes)로 매칭 (map.js의 BENEFIT_COLOR 방식과 동일)
// - pos: SVG 위 마커 좌표 (viewBox 0 0 300 460 기준, 해부학적으로 정확한 위치가 아니라 이해를 돕기 위한 대략적 표시)
// 부위별 "영양소" 목록은 여기 없고 health_map_nutrients 테이블에서 관리자 페이지로 관리해요.
// (관리자 페이지 > 🧍 건강지도 관리)
export const ZONES = [
  { id: 'brain', num: 1, emoji: '🧠', label: '뇌·집중력', keywords: ['두뇌', '기억력', '치매', '집중'],
    blurb: '기억력과 집중력에 도움이 된다고 알려진 성분들이에요.',
    color: '#6366f1', bg: '#ede9fe', pos: { x: 150, y: 8 } },
  { id: 'eye', num: 2, emoji: '👁️', label: '눈', keywords: ['눈', '시력', '안구'],
    blurb: '눈 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#f59e0b', bg: '#fef3c7', pos: { x: 181, y: 16 } },
  { id: 'skinTone', num: 3, emoji: '🌟', label: '피부색·미백', keywords: ['미백', '피부톤'],
    blurb: '피부 톤 관리에 도움이 된다고 알려진 성분들이에요.',
    color: '#fb923c', bg: '#ffedd5', pos: { x: 204, y: 39 } },
  { id: 'sleep', num: 4, emoji: '😴', label: '잠(수면)', keywords: ['수면', '불면'],
    blurb: '숙면에 도움이 된다고 알려진 성분들이에요.',
    color: '#0ea5e9', bg: '#e0f2fe', pos: { x: 212, y: 70 } },
  { id: 'stress', num: 5, emoji: '😌', label: '스트레스·멘탈', keywords: ['스트레스', '신경'],
    blurb: '스트레스 완화에 도움이 된다고 알려진 성분들이에요.',
    color: '#14b8a6', bg: '#ccfbf1', pos: { x: 119, y: 16 } },
  { id: 'scalp', num: 6, emoji: '💆', label: '두피', keywords: ['두피'],
    blurb: '두피 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#a855f7', bg: '#f3e8ff', pos: { x: 96, y: 39 } },
  { id: 'hair', num: 7, emoji: '💇', label: '머리카락', keywords: ['모발', '탈모'],
    blurb: '모발 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#8b5cf6', bg: '#ede9fe', pos: { x: 88, y: 70 } },
  { id: 'heart', num: 8, emoji: '❤️', label: '심장·혈관', keywords: ['심장', '혈관', '혈압', '혈액', '콜레스테롤'],
    blurb: '혈관 건강과 혈압 관리에 도움이 된다고 알려진 성분들이에요.',
    color: '#ef4444', bg: '#fee2e2', pos: { x: 150, y: 122 } },
  { id: 'stomach', num: 9, emoji: '🍽️', label: '위', keywords: ['위', '위장'],
    blurb: '위 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#22c55e', bg: '#dcfce7', pos: { x: 122, y: 158 } },
  { id: 'liver', num: 10, emoji: '🫀', label: '간', keywords: ['간', '해독'],
    blurb: '간 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#65a30d', bg: '#ecfccb', pos: { x: 185, y: 158 } },
  { id: 'gut', num: 11, emoji: '🌿', label: '장', keywords: ['장', '변비', '소화'],
    blurb: '장 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#10b981', bg: '#d1fae5', pos: { x: 150, y: 200 } },
  { id: 'weight', num: 12, emoji: '⚖️', label: '체중·다이어트', keywords: ['체중', '다이어트', '비만'],
    blurb: '체중 관리에 도움이 된다고 알려진 성분들이에요.',
    color: '#d946ef', bg: '#fae8ff', pos: { x: 150, y: 232 } },
  { id: 'skin', num: 13, emoji: '✨', label: '피부(탄력)', keywords: ['피부', '미용', '콜라겐'],
    blurb: '피부 탄력에 도움이 된다고 알려진 성분들이에요.',
    color: '#ec4899', bg: '#fce7f3', pos: { x: 232, y: 175 } },
  { id: 'joint', num: 14, emoji: '🦵', label: '관절', keywords: ['관절'],
    blurb: '관절 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#f59e0b', bg: '#fef3c7', pos: { x: 120, y: 390 } },
  { id: 'bone', num: 15, emoji: '🦴', label: '뼈', keywords: ['뼈', '골다공증'],
    blurb: '뼈 건강에 도움이 된다고 알려진 성분들이에요.',
    color: '#eab308', bg: '#fef9c3', pos: { x: 180, y: 430 } },
  { id: 'immune', num: 16, emoji: '🛡️', label: '면역·항산화', keywords: ['면역', '항산화', '항암'],
    blurb: '면역력과 항산화에 도움이 된다고 알려진 성분들이에요.',
    color: '#16a34a', bg: '#dcfce7', pos: { x: 40, y: 110 } },
]

// 초기 시딩(참고용) — health_map_nutrients 테이블이 비어있을 때 화면이 휑하지 않도록
// 관리자 페이지에서 "기본값 채우기"를 누르면 이 값들이 한 번에 등록돼요.
export const DEFAULT_NUTRIENTS = {
  brain: ['DHA', '오메가3', '레시틴', '비타민B군'],
  eye: ['루테인', '지아잔틴', '비타민A', '안토시아닌'],
  skinTone: ['비타민C', '글루타치온', '나이아신아마이드'],
  sleep: ['멜라토닌', '트립토판', '글리신', '마그네슘'],
  stress: ['마그네슘', '테아닌', '비타민B군', '트립토판'],
  scalp: ['비오틴', '아연', '판토텐산'],
  hair: ['비오틴', '케라틴(단백질)', '철분', '아연'],
  heart: ['오메가3', '칼륨', '코엔자임Q10', '식이섬유'],
  stomach: ['무기질', '식이섬유', '소화효소(브로멜라인 등)'],
  liver: ['타우린', '실리마린', '항산화 성분'],
  gut: ['식이섬유', '유산균(프로바이오틱스)'],
  weight: ['식이섬유', '단백질', '카테킨'],
  skin: ['콜라겐', '비타민C', '코엔자임Q10'],
  joint: ['글루코사민', '콘드로이친', '오메가3', 'MSM'],
  bone: ['칼슘', '비타민D', '마그네슘', '비타민K'],
  immune: ['비타민C', '폴리페놀', '베타카로틴', '아연'],
}
